# coding_agent.py

import asyncio
import os
import subprocess
import sys
import tempfile

from core.base_agent import BaseAgent
from core.event_bus import EventBus
from core.command_queue import CommandQueue


class CodingAgent(BaseAgent):

    AGENT_ID = "coding_agent"

    def __init__(
        self,
        event_bus: EventBus,
        command_queue: CommandQueue
    ):

        super().__init__(
            agent_id=self.AGENT_ID,
            event_bus=event_bus,
            command_queue=command_queue
        )

        self.workspace = "generated_code"

    # ==========================================
    # START
    # ==========================================

    async def on_start(self):

        os.makedirs(
            self.workspace,
            exist_ok=True
        )

        self.register_intent(
            "generate_code",
            self.generate_code
        )

        self.register_intent(
            "execute_code",
            self.execute_code
        )

    # ==========================================
    # STOP
    # ==========================================

    async def on_stop(self):

        pass

    # ==========================================
    # HANDLE COMMAND
    # ==========================================

    async def handle_command(
        self,
        command
    ):

        intent = command.get(
            "intent"
        )

        payload = command.get(
            "payload",
            {}
        )

        if intent in self.intent_handlers:

            return await self.intent_handlers[
                intent
            ](payload)

        return {
            "success": False,
            "message": "Unknown coding intent"
        }

    # ==========================================
    # GENERATE CODE
    # ==========================================

    async def generate_code(
        self,
        payload
    ):

        description = payload.get(
            "description",
            ""
        )

        filename = payload.get(
            "filename",
            "generated_program.py"
        )

        code = f'''
print("Buddy AI Generated Program")
print("Task: {description}")
'''

        filepath = os.path.join(
            self.workspace,
            filename
        )

        with open(
            filepath,
            "w",
            encoding="utf-8"
        ) as file:

            file.write(code)

        return {
            "success": True,
            "filepath": filepath,
            "message": "Code generated successfully"
        }

    # ==========================================
    # EXECUTE CODE
    # ==========================================

    async def execute_code(
        self,
        payload
    ):

        code = payload.get(
            "code",
            ""
        )

        if not code:

            return {
                "success": False,
                "message": "No code provided"
            }

        temp_file = tempfile.NamedTemporaryFile(
            delete=False,
            suffix=".py",
            mode="w",
            encoding="utf-8"
        )

        temp_file.write(code)

        temp_file.close()

        try:

            result = subprocess.run(
                [sys.executable, temp_file.name],
                capture_output=True,
                text=True,
                timeout=20
            )

            return {
                "success": True,
                "stdout": result.stdout,
                "stderr": result.stderr
            }

        except Exception as e:

            return {
                "success": False,
                "message": str(e)
            }

        finally:

            os.unlink(
                temp_file.name
            )
            # ==========================================
# LEGACY COMPATIBILITY
# ==========================================

_dummy_event_bus = EventBus()

_dummy_command_queue = CommandQueue()

_coding_agent = CodingAgent(
    _dummy_event_bus,
    _dummy_command_queue
)

import asyncio

try:

    asyncio.run(
        _coding_agent.on_start()
    )

except:

    pass


def create_python_file(filename):

    result = asyncio.run(

        _coding_agent.generate_code(
            {
                "description": "Generated by Buddy AI",
                "filename": filename
            }
        )
    )

    return result["message"]