"""
God-Tier Email Agent
Connects to Gmail via IMAP/SMTP for full read/write access.
Requires Google App Password.
"""

import smtplib
import imaplib
import email
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
import os

load_dotenv()

GMAIL_ADDRESS = os.getenv("GMAIL_ADDRESS", "your_email@gmail.com")
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD", "your_app_password")

def send_email(to_email: str, subject: str, body: str) -> str:
    """Sends an email using Gmail SMTP. The body can be generated by the AI."""
    if GMAIL_APP_PASSWORD == "your_app_password":
        return "ERROR: Gmail App Password not configured in .env file."
        
    try:
        msg = MIMEMultipart()
        msg['From'] = GMAIL_ADDRESS
        msg['To'] = to_email
        msg['Subject'] = subject
        msg.attach(MIMEText(body, 'plain'))
        
        # Connect to Gmail SMTP server
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
        server.send_message(msg)
        server.quit()
        
        return f"SUCCESS: Email sent to {to_email}. Subject: {subject}"
    except Exception as e:
        return f"Failed to send email: {str(e)}"

def check_inbox(limit: int = 5) -> str:
    """Reads the latest unread emails from the Gmail inbox."""
    if GMAIL_APP_PASSWORD == "your_app_password":
        return "ERROR: Gmail App Password not configured in .env file."
        
    try:
        mail = imaplib.IMAP4_SSL('imap.gmail.com')
        mail.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
        mail.select('inbox')
        
        # Search for all emails
        status, messages = mail.search(None, 'ALL')
        email_ids = messages[0].split()
        
        # Get the latest X emails
        latest_email_ids = email_ids[-limit:]
        
        result_text = f"--- LATEST {limit} EMAILS ---\n\n"
        
        for email_id in reversed(latest_email_ids):
            status, msg_data = mail.fetch(email_id, '(RFC822)')
            for response_part in msg_data:
                if isinstance(response_part, tuple):
                    msg = email.message_from_bytes(response_part[1])
                    subject = msg['subject']
                    sender = msg['from']
                    
                    # Extract body
                    body = ""
                    if msg.is_multipart():
                        for part in msg.walk():
                            content_type = part.get_content_type()
                            if content_type == 'text/plain':
                                body = part.get_payload(decode=True).decode()
                                break
                    else:
                        body = msg.get_payload(decode=True).decode()
                        
                    # Truncate body for reading
                    body_preview = body[:200].replace('\n', ' ') + "..." if len(body) > 200 else body.replace('\n', ' ')
                    result_text += f"From: {sender}\nSubject: {subject}\nBody: {body_preview}\n\n"
        
        mail.logout()
        return result_text
    except Exception as e:
        return f"Failed to read inbox: {str(e)}"
